In [1]:
import numpy as np
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from alg import *

In [3]:
def sympletic_subspace_encoding(Pauli:str):
    N1 = []
    N2 = []
    for w in Pauli:
        if w == 'X':
            N1.append(1)
            N2.append(0)
        elif w == 'Y':
            N1.append(1)
            N2.append(1)
        elif w == 'Z':
            N1.append(0)
            N2.append(1)
        else:
            N1.append(0)
            N2.append(0)
    return np.array(N1+N2)

def subspace_inner_product(a, b):
    N = len(a)//2
    A = np.array([[0,1],[1,0]])
    B = np.identity(N)
    J = np.kron(A,B)
    return np.dot(a, np.dot(J,b)) % 2

def decoding(M):
    Ps = []
    N = M.shape[1]//2
    for v in M:
        P = ''
        for i in range(N):
            if v[i] == 0:
                if v[i+N] == 0: 
                    P += 'I'
                else:
                    P += 'Z'
            else:
                if v[i+N] == 0: 
                    P += 'X'
                else:
                    P += 'Y'
        Ps.append(P)
    return Ps

In [4]:
def remove_zero(E):
    for i,v in reversed(list(enumerate(E))):
        if sum(v) == 0:
            E = np.delete(E, i, 0)
    return E

In [5]:
XX = sympletic_subspace_encoding('XX')
YY = sympletic_subspace_encoding('YY')
ZZ = sympletic_subspace_encoding('ZZ')
E = np.array([XX,YY,ZZ])
print(E)

[[1 1 0 0]
 [1 1 1 1]
 [0 0 1 1]]


In [6]:
E = GF2_Gauss_elimination(E)
print(E)

[[1 1 0 0]
 [0 0 1 1]
 [0 0 0 0]]


In [9]:
p1 = sympletic_subspace_encoding('IZII')
p2 = sympletic_subspace_encoding('XZXI')
p3 = sympletic_subspace_encoding('YZYI')
p4 = sympletic_subspace_encoding('ZIZI')
p5 = sympletic_subspace_encoding('ZZZI')
p6 = sympletic_subspace_encoding('IZIZ')
p7 = sympletic_subspace_encoding('XZXZ')
p8 = sympletic_subspace_encoding('YZYZ')
p9 = sympletic_subspace_encoding('ZIZZ')
p10 = sympletic_subspace_encoding('ZZZZ')

E = np.array([p1,p2,p3,p4,p5,p6,p7,p8,p9,p10])
print(E)

[[0 0 0 0 0 1 0 0]
 [1 0 1 0 0 1 0 0]
 [1 0 1 0 1 1 1 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 1]
 [1 0 1 0 0 1 0 1]
 [1 0 1 0 1 1 1 1]
 [0 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 1 1]]


In [8]:
E = GF2_Gauss_elimination(E)
print(E)

[[1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [13]:
E = gf2elim(E)
print(E)

[[1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [16]:
S = [sympletic_subspace_encoding('ZXZZZXII'), 
sympletic_subspace_encoding('ZYZZZYII'),
sympletic_subspace_encoding('ZIIYZZZY'),
sympletic_subspace_encoding('ZIIXZZZX'),
sympletic_subspace_encoding('IYZZIYII'),
sympletic_subspace_encoding('IXZZIXII'),
sympletic_subspace_encoding('IIYXIIXY'),
sympletic_subspace_encoding('IIYYIIXX'),
sympletic_subspace_encoding('IIXXIIYY'),
sympletic_subspace_encoding('IIXYIIYX'),
sympletic_subspace_encoding('IIIXIZZX'),
sympletic_subspace_encoding('IXYIIYXI'),
sympletic_subspace_encoding('IXXIIYYI'),
sympletic_subspace_encoding('IYYIIXXI'),
sympletic_subspace_encoding('IIIYIZZY'),
sympletic_subspace_encoding('IYXIIXYI'),
sympletic_subspace_encoding('IIYZZZYI'),
sympletic_subspace_encoding('IIXZZZXI')]
E = np.array(S)
E

array([[0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0,

In [15]:
E = GF2_Gauss_elimination(E)
print(E)

[[0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [17]:
E = gf2elim(E)
E = remove_zero(E)
print("Found {} basis.".format(len(E)))
print(E)

Found 8 basis.
[[0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]]


In [36]:
Tau = decoding(E)

['IXIIIXZZ',
 'IIXIIZXZ',
 'IIIXIZZX',
 'ZIIIIIII',
 'IZIIIZII',
 'IIZIIIZI',
 'IIIZIIIZ',
 'IIIIZIII']

In [97]:
X = np.array([[3,1,-1],[1,-1,1],[2,1,1]], dtype='float')
b = np.array([1,-3,0],dtype='float')

In [99]:
A, b = Gauss_elimination(X, b, return_b=True, pivot=False, back_substitution=True)
print(A)
print(b)
x = b/np.diag(A)
print("x={}".format(x))

[[ 3.          0.          0.        ]
 [ 0.         -1.33333333  0.        ]
 [ 0.          0.          2.        ]]
[-1.5        -2.33333333 -1.5       ]
x=[-0.5   1.75 -0.75]
